# Generated by Django 5.1.2 on 2024-10-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='crypto_address',
        ),
    ]
