# Generated by Django 5.1.2 on 2024-10-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_confirmrequest_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
