# Generated by Django 5.1.2 on 2024-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_active_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('seller', 'Продавец'), ('admin', 'Администратор сайта'), ('root-admin', 'ГА сайта')], default='user'),
        ),
    ]
