# Generated by Django 5.1.2 on 2024-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_user_products_cart_alter_user_email_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('temp_user', 'Временный пользователь'), ('user', 'Пользователь'), ('seller', 'Продавец'), ('admin', 'Администратор сайта'), ('root-admin', 'ГА сайта')], default='user'),
        ),
    ]
