# Generated by Django 5.1.2 on 2024-10-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_seller_is_verified_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='sellers',
        ),
        migrations.AlterModelTable(
            name='token',
            table='tokens',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
