# Generated by Django 5.1.2 on 2024-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_seller_table_alter_token_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
