# Generated by Django 5.1.2 on 2024-10-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_seller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
