# Generated by Django 5.1.2 on 2024-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
