# Generated by Django 5.1.2 on 2024-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmrequest',
            name='token',
        ),
        migrations.AddField(
            model_name='confirmrequest',
            name='code',
            field=models.CharField(default='123456'),
            preserve_default=False,
        ),
    ]
