# Generated by Django 5.1.2 on 2024-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_remove_confirmrequest_token_confirmrequest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmrequest',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmrequest',
            name='type',
            field=models.CharField(choices=[('confirm', 'Подтверждение почты'), ('reset-request', 'Сброс пароля'), ('password-set', 'Установка нового пароля')], default='confirm'),
        ),
    ]
