# Generated by Django 5.1.2 on 2024-11-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_remove_user_photo_user_avatar_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.user'),
        ),
    ]
