# Generated by Django 5.1.2 on 2024-11-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_referralprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralProfile',
        ),
    ]
