# Generated by Django 5.1.2 on 2024-11-11 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_delete_referralprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_link',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
