# Generated by Django 5.1.2 on 2024-11-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_user_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
