# Generated by Django 5.1.2 on 2024-11-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_seller_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
