# Generated by Django 5.1.2 on 2024-12-03 23:45

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0035_userip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_link",
            field=models.CharField(
                default=Users.models.get_unique_referral_id, editable=False, unique=True
            ),
        ),
    ]
