# Generated by Django 5.1.2 on 2024-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('fr', 'French'), ('ja', 'Japan'), ('es', 'Espanol'), ('ko', 'Korean'), ('ua', 'Ukrainian'), ('de', 'German'), ('zh', 'hz'), ('hi', 'hello navernoe'), ('ar', 'Arabskiy')], default='en'),
        ),
    ]
