# Generated by Django 5.1.2 on 2024-10-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0005_remove_transaction_product_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service_data', models.JSONField(default=dict)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('count', models.IntegerField(default='')),
                ('provider_code', models.CharField(choices=[('lightning', 'LOLA'), ('bob', 'BOB'), ('proxy_drop_pull_1', 'PROXY_PROP_PULL_1'), ('proxy_drop_pull_2', 'PROXY_PROP_PULL_2')], default='', max_length=255)),
                ('service_type', models.CharField(choices=[('residential', 'RESIDENTIAL-PREMIUM'), ('isp', 'ISP'), ('data center', 'SHARED-DATACENTER')], default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('enabled', 'Enabled')], default='active', max_length=50)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.purchase')),
            ],
        ),
    ]
