# Generated by Django 5.1.2 on 2024-10-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_purchase_buyer_remove_purchase_seller_and_more'),
        ('Proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.transaction'),
        ),
    ]
