# Generated by Django 5.1.2 on 2024-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0003_alter_proxypurchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypurchase',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proxypurchase',
            name='status',
            field=models.CharField(choices=[('process', 'Processing'), ('active', 'Active'), ('enabled', 'Enabled'), ('expired', 'Expired')], default='process', max_length=50),
        ),
    ]
