# Generated by Django 5.1.2 on 2024-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0005_proxypurchase_extend_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypurchase',
            name='status',
            field=models.CharField(choices=[('process', 'Processing'), ('active', 'Active'), ('enabled', 'Enabled'), ('expired', 'Expired'), ('bandwith_left', 'BANDWITH LEFT')], default='process', max_length=50),
        ),
    ]
