# Generated by Django 5.1.2 on 2024-10-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_rename_message_transaction_buyer_message_and_more'),
        ('Proxy', '0006_alter_proxypurchase_status'),
        ('Users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxypurchase',
            name='provider_code',
        ),
        migrations.RemoveField(
            model_name='proxypurchase',
            name='service_type',
        ),
        migrations.AddField(
            model_name='proxypurchase',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Users.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxypurchase',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Main.category'),
            preserve_default=False,
        ),
    ]
