# Generated by Django 5.1.2 on 2024-10-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0007_remove_proxypurchase_provider_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxypurchase',
            name='provider',
        ),
    ]
