# Generated by Django 5.1.2 on 2024-10-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0008_remove_proxypurchase_provider'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proxypurchase',
            table='proxy_purchases',
        ),
    ]
