# Generated by Django 5.1.2 on 2024-10-27 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0009_alter_proxypurchase_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxypurchase',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 16, 54, 56, 94466)),
        ),
    ]
