# Generated by Django 5.1.2 on 2024-10-27 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0014_alter_proxypurchase_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypurchase',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 24)),
        ),
    ]
