# Generated by Django 5.1.2 on 2024-11-02 16:47

import Proxy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proxy', '0016_alter_proxypurchase_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypurchase',
            name='expiration_date',
            field=models.DateTimeField(auto_created=True, default=Proxy.models.get_expiration_date),
        ),
    ]
