# Generated by Django 5.1.2 on 2024-12-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proxy", "0017_alter_proxypurchase_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxypurchase",
            name="credentials_counter",
            field=models.IntegerField(default=0),
        ),
    ]
