# Generated by Django 5.1.2 on 2024-10-17 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька')])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('5bd06a3a-73ac-4957-9aaa-ec32d2eb6f22'), unique=True)),
                ('amount', models.FloatField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.seller')),
            ],
        ),
    ]
