# Generated by Django 5.1.2 on 2024-10-17 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6fa6417d-20b4-4186-925c-3a6a2409483d'), unique=True),
        ),
    ]
