# Generated by Django 5.1.2 on 2024-10-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_transaction_uuid'),
        ('Users', '0002_remove_seller_crypto_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('paid_over', 'Оплачено больше'), ('wrong_amount', 'Недоплата'), ('process', 'В процессе'), ('confirmation_check', 'Проверка подтверждений'), ('confirmations', 'Подтверждения'), ('wrong_amount_waiting', 'Ожидание доплаты'), ('check', 'Ожидание блокчейна'), ('fail', 'Ошибка оплаты'), ('cancel', 'Отмена оплаты'), ('system_fail', 'Системная ошибка'), ('refund_process', 'Возврат в процессе'), ('refund_fail', 'Ошибка возврата'), ('refund_paid', 'Возврат проведён'), ('locked', 'Средства заблокированы из-за AML')], default='check'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.category'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.seller')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.transaction')),
            ],
        ),
    ]
