# Generated by Django 5.1.2 on 2024-10-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_transaction_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='to_user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='from_user',
            new_name='seller',
        ),
    ]
