# Generated by Django 5.1.2 on 2024-10-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_purchase_buyer_remove_purchase_seller_and_more'),
        ('Proxy', '0002_alter_proxypurchase_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
