# Generated by Django 5.1.2 on 2024-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_rename_message_transaction_buyer_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.JSONField(default={1: 1, 4: 0.5}),
            preserve_default=False,
        ),
    ]
