# Generated by Django 5.1.2 on 2024-10-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_remove_product_price_product_prices'),
        ('Proxy', '0008_remove_proxypurchase_provider'),
        ('Users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Purchase',
        ),
        migrations.CreateModel(
            name='BalanceTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('paid_over', 'Оплачено больше'), ('wrong_amount', 'Недоплата'), ('process', 'В процессе'), ('confirmation_check', 'Проверка подтверждений'), ('confirmations', 'Подтверждения'), ('wrong_amount_waiting', 'Ожидание доплаты'), ('check', 'Ожидание блокчейна'), ('fail', 'Ошибка оплаты'), ('cancel', 'Отмена оплаты'), ('system_fail', 'Системная ошибка'), ('refund_process', 'Возврат в процессе'), ('refund_fail', 'Ошибка возврата'), ('refund_paid', 'Возврат проведён'), ('locked', 'Средства заблокированы из-за AML')], default='check')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.user')),
            ],
        ),
    ]
