# Generated by Django 5.1.2 on 2024-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_rename_transaction_purchase_balancetopup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancetopup',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AddField(
            model_name='balancetopup',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
            preserve_default=False,
        ),
    ]
