# Generated by Django 5.1.2 on 2024-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_purchase_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
