# Generated by Django 5.1.2 on 2024-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelTable(
            name='balancetopup',
            table='balance_top_ups',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
        migrations.AlterModelTable(
            name='usercart',
            table='users_carts',
        ),
    ]
