# Generated by Django 5.1.2 on 2024-10-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_product_in_stock_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька')], max_length=100, null=True),
        ),
    ]
