# Generated by Django 5.1.2 on 2024-10-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/products/%Y/%m/%d/'),
        ),
    ]
