# Generated by Django 5.1.2 on 2024-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='amount',
            field=models.FloatField(),
        ),
    ]
