# Generated by Django 5.1.2 on 2024-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_file_review_rating_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
