# Generated by Django 5.1.2 on 2024-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_purchase_product_options_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька'), ('soft', 'Софт')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька'), ('soft', 'Софт')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька'), ('soft', 'Софт')]),
        ),
    ]
