# Generated by Django 5.1.2 on 2024-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='options',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
