# Generated by Django 5.1.2 on 2024-11-02 16:47

import Main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_alter_usercart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптовалютой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптовалютой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField()),
                ('hash', models.CharField()),
                ('network', models.CharField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=14)),
                ('decimal', models.IntegerField(blank=True, null=True)),
                ('expiration_dt', models.DateTimeField(default=Main.models.get_exp_invoice)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.purchase')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
