# Generated by Django 5.1.2 on 2024-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_alter_balancetopup_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchase',
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchases',
            field=models.ManyToManyField(to='Main.purchase'),
        ),
    ]
