# Generated by Django 5.1.2 on 2024-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_remove_invoice_purchase_invoice_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
    ]
