# Generated by Django 5.1.2 on 2024-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_remove_productdata_file_productdata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('proxy', 'Прокси'), ('account', 'Аккаунт'), ('kyc', 'Верификация кошелька'), ('soft', 'Софт')], db_index=True),
        ),
    ]
