# Generated by Django 5.1.2 on 2024-11-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_rename_productdata_accountdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountData',
            new_name='ProductData',
        ),
        migrations.AlterModelTable(
            name='productdata',
            table='products_data',
        ),
    ]
