# Generated by Django 5.1.2 on 2024-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0045_alter_purchase_seller_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
    ]
