# Generated by Django 5.1.2 on 2024-11-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_alter_balancetopup_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
    ]
