# Generated by Django 5.1.2 on 2024-11-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_alter_balancetopup_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(auto_created=True, default='954a107b-bdb0-4a71-a01c-c67e77fa6a04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптовалютой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Баланс аккаунта'), ('crypto', 'Криптовалютой'), ('cryptomus', 'Криптовалютой через Cryptomus')], default='cryptomus'),
        ),
    ]
