# Generated by Django 5.1.2 on 2024-11-09 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_invoice_uuid_alter_balancetopup_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_amount',
            field=models.FloatField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
