# Generated by Django 5.1.2 on 2024-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0050_invoice_balance_top_up_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hash',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='network',
            field=models.CharField(blank=True, null=True),
        ),
    ]
