# Generated by Django 5.1.2 on 2024-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0052_alter_invoice_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='purchase_amount',
            new_name='amount_crypto',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_usd',
            field=models.FloatField(db_index=True, default=1.0),
            preserve_default=False,
        ),
    ]
