# Generated by Django 5.1.2 on 2024-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0055_referraltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
