# Generated by Django 5.1.2 on 2024-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0057_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltransaction',
            name='type',
            field=models.CharField(choices=[('accrual', 'Начисление'), ('withdraw', 'Вывод')], db_index=True, default='accrual'),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='amount',
            field=models.FloatField(db_index=True),
        ),
    ]
