# Generated by Django 5.1.2 on 2024-11-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0060_purchase_data_file_alter_category_type_and_more'),
        ('Users', '0033_tguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField()),
                ('params', models.TextField()),
                ('response', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.user')),
            ],
            options={
                'db_table': 'admin_actions',
            },
        ),
    ]
