# Generated by Django 5.1.2 on 2024-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0061_remove_purchase_data_file_adminaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaction',
            name='response',
        ),
        migrations.AddField(
            model_name='adminaction',
            name='response_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
