# Generated by Django 5.1.2 on 2024-12-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0063_remove_purchase_data_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="referraltransaction",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Main.purchase",
            ),
        ),
    ]
