# Generated by Django 5.1.2 on 2024-12-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0066_alter_balancetopup_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancetopup",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("balance", "Balance"),
                    ("crypto", "Gemups"),
                    ("cryptomus", "Cryptomus"),
                    ("stripe", "Stripe"),
                ],
                default="cryptomus",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("balance", "Balance"),
                    ("crypto", "Gemups"),
                    ("cryptomus", "Cryptomus"),
                    ("stripe", "Stripe"),
                ],
                default="cryptomus",
            ),
        ),
    ]
