# Generated by Django 5.1.2 on 2024-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0067_alter_balancetopup_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetopup',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Balance'), ('cryptomus', 'Cryptomus'), ('crypto', 'CustomPay'), ('stripe', 'Stripe(Card)')], default='cryptomus'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('balance', 'Balance'), ('cryptomus', 'Cryptomus'), ('crypto', 'CustomPay'), ('stripe', 'Stripe(Card)')], default='cryptomus'),
        ),
    ]
